-- Insert clients from CSV
INSERT INTO Clients (
name, 
region, location, 
region_id, countryId, contact, status, added_by) VALUES
('Naivas Utawala', 'Nairobi', 'Utawala', 1, 1, 'N/A', 1, 1)
,('Quickmart Express Utawala', 'Nairobi', 'Utawala', 1, 1, 'N/A', 1, 1)
,('Quickmart Main Utawala', 'Nairobi', 'Utawala', 1, 1, 'N/A', 1, 1)
,('Magunas Utawala', 'Nairobi', 'Utawala', 1, 1, 'N/A', 1, 1)
,('Ottomatt Githunguri/Utawala', 'Nairobi', 'Utawala', 1, 1, 'N/A', 1, 1)
,('Weacon Githunguri/Utawala', 'Nairobi', 'Utawala', 1, 1, 'N/A', 1, 1)
,('Quickmart Embakasi', 'Nairobi', 'Embakasi', 1, 1, 'N/A', 1, 1)
,('Naivas Nyayo Embakasi', 'Nairobi', 'Embakasi', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi Express', 'Nairobi', 'Express', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi Transami', 'Nairobi', 'Transami', 1, 1, 'N/A', 1, 1)
,('Waeconmatt Makuti', 'Nairobi', 'Makuti', 1, 1, 'N/A', 1, 1)
,('Quickmart Pipeline', 'Nairobi', 'Pipeline', 1, 1, 'N/A', 1, 1)
,('Quickmart Outering', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Naivas Tassia', 'Nairobi', 'Tassia', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi chapchap', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi Pipeline', 'Nairobi', 'Pipeline', 1, 1, 'N/A', 1, 1)
,('Quickmart Fedha', 'Nairobi', 'Fedha', 1, 1, 'N/A', 1, 1)
,('Quickmart Donholm', 'Nairobi', 'Donholm', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi Tassia', 'Nairobi', 'Tassia', 1, 1, 'N/A', 1, 1)
,('Waeconmatt Fedha', 'Nairobi', 'Fedha', 1, 1, 'N/A', 1, 1)
,('Waeconmatt Tassia', 'Nairobi', 'Tassia', 1, 1, 'N/A', 1, 1)
,('Quickmart Buruburu', 'Nairobi', 'Buruburu', 1, 1, 'N/A', 1, 1)
,('Naivas T-square', 'Nairobi', 'Buruburu', 1, 1, 'N/A', 1, 1)
,('Dimples Umoja', 'Nairobi', 'Umoja', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi Umoja', 'Nairobi', 'Umoja', 1, 1, 'N/A', 1, 1)
,('Skymart Umoja Market', 'Nairobi', 'Umoja', 1, 1, 'N/A', 1, 1)
,('Naivas Greenspan', 'Nairobi', 'Greenspan', 1, 1, 'N/A', 1, 1)
,('Cleanshelf Shujaa', 'Nairobi', 'Shujaa', 1, 1, 'N/A', 1, 1)
,('Naivas Eastgate', 'Nairobi', 'Eastgate', 1, 1, 'N/A', 1, 1)
,('Skymart Kayole', 'Nairobi', 'Kayole', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi Kayole Soweto', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Naivas Komarock', 'Nairobi', 'Komarock', 1, 1, 'N/A', 1, 1)
,('Cleanshelf Kmall', 'Nairobi', 'Kmall', 1, 1, 'N/A', 1, 1)
,('Naivas Saika', 'Nairobi', 'Saika', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi -Junction', 'Nairobi', 'Junction', 1, 1, 'N/A', 1, 1)
,('Magunas kayo junction', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Naivas Umoja', 'Nairobi', 'Umoja', 1, 1, 'N/A', 1, 1)
,('Quickmart Outering 2', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Skymart Umoja 2', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Skymart Tena', 'Nairobi', 'Tena', 1, 1, 'N/A', 1, 1)
,('Skymart Moi', 'Nairobi', 'Moi', 1, 1, 'N/A', 1, 1)
,('Quickmart Ruai', 'Nairobi', 'Ruai', 1, 1, 'N/A', 1, 1)
,('Weacon Kamulu', 'Nairobi', 'Kamulu', 1, 1, 'N/A', 1, 1)
,('Otomatt Mutalia', 'Nairobi', 'Mutalia', 1, 1, 'N/A', 1, 1)
,('Eastmatt Tala', 'Nairobi', 'Tala', 1, 1, 'N/A', 1, 1)
,('Fastmatt Mtaani', 'Nairobi', 'Mtaani', 1, 1, 'N/A', 1, 1)
,('Skymart Tala', 'Nairobi', 'Tala', 1, 1, 'N/A', 1, 1)
,('Fastmatt Kipawa', 'Nairobi', 'Kipawa', 1, 1, 'N/A', 1, 1)
,('Fastmatt Tala', 'Nairobi', 'Tala', 1, 1, 'N/A', 1, 1)
,('Carrefour Eastleigh', 'Nairobi', 'Eastleigh', 1, 1, 'N/A', 1, 1)
,('Naivas Buruburu', 'Nairobi', 'Buruburu', 1, 1, 'N/A', 1, 1)
,('Naivas jogoo road', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Magunas jogoo road', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Naivas Ruai', 'Nairobi', 'Ruai', 1, 1, 'N/A', 1, 1)
,('Ottomatt Mutalia', 'Nairobi', 'Mutalia', 1, 1, 'N/A', 1, 1)
,('Waeconmatt kingori', 'Nairobi', 'kingori', 1, 1, 'N/A', 1, 1)
,('Waeconmatt Joska', 'Nairobi', 'Joska', 1, 1, 'N/A', 1, 1)
,('Waeconmatt malaa', 'Nairobi', 'malaa', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi chokaa', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Quickmart joska', 'Nairobi', 'joska', 1, 1, 'N/A', 1, 1)
,('Naivas Super Centre', 'Nairobi', 'Centre', 1, 1, 'N/A', 1, 1)
,('Naivas Old Machakos', 'Nairobi', 'Machakos', 1, 1, 'N/A', 1, 1)
,('Quickmart Kitui', 'Nairobi', 'Kitui', 1, 1, 'N/A', 1, 1)
,('Naivas kitui', 'Nairobi', 'kitui', 1, 1, 'N/A', 1, 1)
,('Magunas Kitui', 'Nairobi', 'Kitui', 1, 1, 'N/A', 1, 1)
,('Naivas Capital Centre', 'Nairobi', 'Mombasa Road', 1, 1, 'N/A', 1, 1)
,('Naivas South C', 'Nairobi', 'South C', 1, 1, 'N/A', 1, 1)
,('Cleanshelf South C', 'Nairobi', 'South C', 1, 1, 'N/A', 1, 1)
,('Carrefour Nextgen', 'Nairobi', 'Nextgen', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi South B', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Naivas Mavoko', 'Nairobi', 'Mavoko', 1, 1, 'N/A', 1, 1)
,('Chandarana Signature', 'Nairobi', 'Signature', 1, 1, 'N/A', 1, 1)
,('Skymart Mlolongo', 'Nairobi', 'Mlolongo', 1, 1, 'N/A', 1, 1)
,('Cleanshelf Greenhouse', 'Nairobi', 'Adams Arcade', 1, 1, 'N/A', 1, 1)
,('Quickmart Mlolongo', 'Nairobi', 'Mlolongo', 1, 1, 'N/A', 1, 1)
,('Chandarana Crystal', 'Nairobi', 'Crystal', 1, 1, 'N/A', 1, 1)
,('Quickmart pioneer Machakos', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Quickmart Express Machakos', 'Nairobi', 'Machakos', 1, 1, 'N/A', 1, 1)
,('Raphymart', 'Nairobi', 'Raphymart', 1, 1, 'N/A', 1, 1)
,('Massmart', 'Nairobi', 'Massmart', 1, 1, 'N/A', 1, 1)
,('Ngooni', 'Nairobi', 'Ngooni', 1, 1, 'N/A', 1, 1)
,('Skymart Junction', 'Nairobi', 'Junction', 1, 1, 'N/A', 1, 1)
,('Naivas Gateway Mall', 'Nairobi', 'Mombasa Road', 1, 1, 'N/A', 1, 1)
,('Naivas Airport', 'Nairobi', 'Airport', 1, 1, 'N/A', 1, 1)
,('Naivas Katani', 'Nairobi', 'Katani', 1, 1, 'N/A', 1, 1)
,('Eastmatt Kitengela', 'Nairobi', 'Kitengela', 1, 1, 'N/A', 1, 1)
,('Naivas Kitengela', 'Nairobi', 'Kitengela', 1, 1, 'N/A', 1, 1)
,('Quickmart Kitengela', 'Nairobi', 'Kitengela', 1, 1, 'N/A', 1, 1)
,('Eastmatt Kajiado', 'Nairobi', 'Kajiado', 1, 1, 'N/A', 1, 1)
,('Powerstar Kitengela', 'Nairobi', 'Kitengela', 1, 1, 'N/A', 1, 1)
,('Waeconmatt Kitengela', 'Nairobi', 'Kitengela', 1, 1, 'N/A', 1, 1)
,('Carrefour South field', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Naivas Imaara', 'Nairobi', 'Imaara', 1, 1, 'N/A', 1, 1)
,('Quickmart Mombasa rd', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi Njenga', 'Nairobi', 'Njenga', 1, 1, 'N/A', 1, 1)
,('Naivas Express Embakasi', 'Nairobi', 'Embakasi', 1, 1, 'N/A', 1, 1)
,('Carrefour Ruiru', 'Nairobi', 'Ruiru', 1, 1, 'N/A', 1, 1)
,('Quickmart Ruiru', 'Nairobi', 'Ruiru', 1, 1, 'N/A', 1, 1)
,('Naivas Ananas', 'Nairobi', 'Ananas', 1, 1, 'N/A', 1, 1)
,('Magunas Thika', 'Nairobi', 'Thika', 1, 1, 'N/A', 1, 1)
,('Waeconmatt Jomoko', 'Nairobi', 'Jomoko', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi Weitaithie', 'Nairobi', 'Weitaithie', 1, 1, 'N/A', 1, 1)
,('Chokamat juja', 'Nairobi', 'juja', 1, 1, 'N/A', 1, 1)
,('Mathais Matco', 'Nairobi', 'Matco', 1, 1, 'N/A', 1, 1)
,('Naivas Kahawa Sukari', 'Nairobi', 'Sukari', 1, 1, 'N/A', 1, 1)
,('Quickmart Kahawa Sukari', 'Nairobi', 'Sukari', 1, 1, 'N/A', 1, 1)
,('Naivas Githurai 45', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Cleanshelf Wendani', 'Nairobi', 'Wendani', 1, 1, 'N/A', 1, 1)
,('Magunas Wendani', 'Nairobi', 'Wendani', 1, 1, 'N/A', 1, 1)
,('Naivas Northview', 'Nairobi', 'Northview', 1, 1, 'N/A', 1, 1)
,('Quickmart Thome', 'Nairobi', 'Thome', 1, 1, 'N/A', 1, 1)
,('Muhindi Mweusi Kariobangi', 'Nairobi', 'Kariobangi', 1, 1, 'N/A', 1, 1)
,('Leester pioneer', 'Nairobi', 'pioneer', 1, 1, 'N/A', 1, 1)
,('Leester Githurai', 'Nairobi', 'Githurai', 1, 1, 'N/A', 1, 1)
,('Naivas Lackey Summer', 'Nairobi', 'Summer', 1, 1, 'N/A', 1, 1)
,('Quickmart OTC', 'Nairobi', 'OTC', 1, 1, 'N/A', 1, 1)
,('Quickmart mfangano', 'Nairobi', 'mfangano', 1, 1, 'N/A', 1, 1)
,('Eastmatt Mfangano', 'Nairobi', 'Mfangano', 1, 1, 'N/A', 1, 1)
,('Mathais OTC', 'Nairobi', 'OTC', 1, 1, 'N/A', 1, 1)
,('Eastmatt River road', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Quickmart pioneer', 'Nairobi', 'pioneer', 1, 1, 'N/A', 1, 1)
,('Naivas Agakhan walk', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Naivas Ronald Ngala', 'Nairobi', 'Ngala', 1, 1, 'N/A', 1, 1)
,('Chandarana Diamond', 'Nairobi', 'Diamond', 1, 1, 'N/A', 1, 1)
,('Chandarana Highridge', 'Nairobi', 'Highridge', 1, 1, 'N/A', 1, 1)
,('Naivas West', 'Nairobi', 'West', 1, 1, 'N/A', 1, 1)
,('Naivas Ojijo', 'Nairobi', 'Ojijo', 1, 1, 'N/A', 1, 1)
,('Naivas Mwanzi', 'Nairobi', 'Mwanzi', 1, 1, 'N/A', 1, 1)
,('Quickmart West', 'Nairobi', 'West', 1, 1, 'N/A', 1, 1)
,('Carrefour St Ellies CBD', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Naivas Lifestyle', 'Nairobi', 'Karen', 1, 1, 'N/A', 1, 1)
,('Naivas Muindimbingu', 'Nairobi', 'Muindimbingu', 1, 1, 'N/A', 1, 1)
,('Eastmatt Tom Mboya', 'Nairobi', 'Mboya', 1, 1, 'N/A', 1, 1)
,('Quickmart Tom mboya', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Carrefour Rongai', 'Nairobi', 'Rongai', 1, 1, 'N/A', 1, 1)
,('Naivas Maiyan', 'Nairobi', 'Maiyan', 1, 1, 'N/A', 1, 1)
,('Quickmart Kiserian', 'Nairobi', 'Kiserian', 1, 1, 'N/A', 1, 1)
,('Quickmart Main', 'Nairobi', 'Main', 1, 1, 'N/A', 1, 1)
,('Quickmart Express Rongai', 'Nairobi', 'Rongai', 1, 1, 'N/A', 1, 1)
,('Naivas Langata', 'Nairobi', 'Langata', 1, 1, 'N/A', 1, 1)
,('Quickmart Tmall', 'Nairobi', 'Tmall', 1, 1, 'N/A', 1, 1)
,('Cleanshelf Langata', 'Nairobi', 'Langata', 1, 1, 'N/A', 1, 1)
,('Naivas Medlink', 'Nairobi', 'Langata', 1, 1, 'N/A', 1, 1)
,('Carrefour Galleria', 'Nairobi', 'Galleria', 1, 1, 'N/A', 1, 1)
,('Chandarana The well', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Naivas Home ground', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Naivas Ngong 2', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Cleanshelf Ngong', 'Nairobi', 'Ngong', 1, 1, 'N/A', 1, 1)
,('Magunas Ngong', 'Nairobi', 'Ngong', 1, 1, 'N/A', 1, 1)
,('Mathai Ngong', 'Nairobi', 'Ngong', 1, 1, 'N/A', 1, 1)
,('Quickmatt Milele', 'Nairobi', 'Milele', 1, 1, 'N/A', 1, 1)
,('Skymart Matasia', 'Nairobi', 'Matasia', 1, 1, 'N/A', 1, 1)
,('Naivas Tilisi', 'Nairobi', 'Tilisi', 1, 1, 'N/A', 1, 1)
,('Self ridges', 'Nairobi', 'Kikuyu', 1, 1, 'N/A', 1, 1)
,('Carrefour Sarit', 'Nairobi', 'Sarit', 1, 1, 'N/A', 1, 1)
,('Carrefour Spring Valley', 'Nairobi', 'Kabete', 1, 1, 'N/A', 1, 1)
,('Chandarana ABC', 'Nairobi', 'Westlands', 1, 1, 'N/A', 1, 1)
,('Chandarana Azlea', 'Nairobi', 'Azalea', 1, 1, 'N/A', 1, 1)
,('Naivas Prestige', 'Nairobi', 'Prestige', 1, 1, 'N/A', 1, 1)
,('Chandarana yaya', 'Nairobi', 'yaya', 1, 1, 'N/A', 1, 1)
,('Naivas Kilimani', 'Nairobi', 'Kilimani', 1, 1, 'N/A', 1, 1)
,('Naivas Wood Avenue', 'Nairobi', 'Avenue', 1, 1, 'N/A', 1, 1)
,('Safeways Hurlingham', 'Nairobi', 'Hurlingham', 1, 1, 'N/A', 1, 1)
,('Carrefour Valley Arcade', 'Nairobi', 'Valley Arcade', 1, 1, 'N/A', 1, 1)
,('Naivas Lavington', 'Nairobi', 'Lavington', 1, 1, 'N/A', 1, 1)
,('Cleanshelf Lavington', 'Nairobi', 'Lavington', 1, 1, 'N/A', 1, 1)
,('Chandarana Lavington', 'Nairobi', 'Lavington', 1, 1, 'N/A', 1, 1)
,('Naivas Kangemi', 'Nairobi', 'Kangemi', 1, 1, 'N/A', 1, 1)
,('Naivas Mountain View', 'Nairobi', 'Waiyaki way', 1, 1, 'N/A', 1, 1)
,('Naivas Riruta', 'Nairobi', 'Riruta', 1, 1, 'N/A', 1, 1)
,('Quickmart Waithaka', 'Nairobi', 'Waithaka', 1, 1, 'N/A', 1, 1)
,('Skymart Kawangware', 'Nairobi', 'Kawangware', 1, 1, 'N/A', 1, 1)
,('Naivas Ciata', 'Nairobi', 'Ciata', 1, 1, 'N/A', 1, 1)
,('Quickmart Kiambu road', 'Nairobi', 'Outer Ring Road', 1, 1, 'N/A', 1, 1)
,('Chandarana Ridgeways', 'Nairobi', 'Ridgeways', 1, 1, 'N/A', 1, 1)
,('Chandarana Mobil', 'Nairobi', '', 1, 1, 'N/A', 1, 1)
,('Carrefour GTC', 'Nairobi', '', 1, 1, 'N/A', 1, 1)
,('Chandarana Riverside', 'Nairobi', 'Riverside', 1, 1, 'N/A', 1, 1)
,('Chandarana Ngara', 'Nairobi', 'Ngara', 1, 1, 'N/A', 1, 1)
,('Cleanshelf Chiromo', 'Nairobi', 'Chiromo', 1, 1, 'N/A', 1, 1)
,('Quickmart Kileleshwa', 'Nairobi', 'Kileleshwa', 1, 1, 'N/A', 1, 1)
,('Carrefour Westgate', 'Nairobi', 'Westgate', 1, 1, 'N/A', 1, 1)
,('Carrefour Rhapta', 'Nairobi', 'Rhapta Road', 1, 1, 'N/A', 1, 1)
,('Chandarana Rhapta Road', 'Nairobi', 'Rhapta Road', 1, 1, 'N/A', 1, 1)
,('Quickmart Waiyaki Way', 'Nairobi', 'Waiyaki way', 1, 1, 'N/A', 1, 1)
,('Naivas Uthiru', 'Nairobi', 'Uthiru', 1, 1, 'N/A', 1, 1)
,('Leester Kinoo', 'Nairobi', 'Kinoo', 1, 1, 'N/A', 1, 1)
,('Carrefour Rhunda', 'Nairobi', 'Rhunda', 1, 1, 'N/A', 1, 1)
,('Naivas Thindigwa', 'Nairobi', 'Thindigwa', 1, 1, 'N/A', 1, 1)
,('Naivas Kiambu', 'Nairobi', 'Kiambu', 1, 1, 'N/A', 1, 1)
,('Cleanshelf Kiambu', 'Nairobi', 'Kiambu', 1, 1, 'N/A', 1, 1)
,('Chandarana Redhill', 'Nairobi', 'Redhill', 1, 1, 'N/A', 1, 1)
,('Magunas Gigiri', 'Nairobi', 'Gigiri', 1, 1, 'N/A', 1, 1)
,('Carrefour Village Market', 'Nairobi', 'Limuru Rd', 1, 1, 'N/A', 1, 1)
,('Quickmart Ruaka', 'Nairobi', 'Ruaka', 1, 1, 'N/A', 1, 1)
,('Chandarana Thigiri', 'Nairobi', 'Thigiri', 1, 1, 'N/A', 1, 1)
,('Magunas Ndenderu', 'Nairobi', 'Ndenderu', 1, 1, 'N/A', 1, 1)
,('Carrefour Two Rivers', 'Nairobi', 'Limuru Rd', 1, 1, 'N/A', 1, 1)
,('Cleanshelf Ruaka', 'Nairobi', 'Ruaka', 1, 1, 'N/A', 1, 1)
,('Chandarana Rosslyn', 'Nairobi', 'Westlands', 1, 1, 'N/A', 1, 1)
;
